### ISSUE TITLE
Infografía Hilos

### ISSUE THREAD

**Issue by MariaC232** [SistemasTecTlaxiaco/infografia-de-hilos-MariaC232#2]
[Hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-MariaC232/files/6462758/Hilos.pdf)

**Comment by Ferch0419** [comment]
Excelente trabajo. Calificación: 20/20. Calificado por Fernando Miguel López

**Comment by josealfredo79** [comment]
Bien hecho y revisado
